name: Chimerical Soup
favicon: null
layout_spectrum: 0.53907
typography_spectrum: 0.40155
title: I Have Excite!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0808'
    - '#756254'
    - '#b8a390'
    - '#edece8'
    - '#f6c9a6'
  brandStrength: 0.18322552926838398
  lightness: 0.5021654386073351
  saturation: 0.8417660396080464
  rhythmicContrast: 0.910454043885693
purpose: []
